import { useEffect, useMemo, useState } from "react";
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation, useParams } from "react-router-dom";
import { ArrowRight, ExternalLink, Github, Linkedin, Mail, Menu, Phone, X } from "lucide-react";
import { capabilities, profile, projects, type Project } from "./data";
import "./styles.css";

const nav = [["/", "Home"], ["/work", "Work"], ["/capabilities", "Capabilities"], ["/about", "About"], ["/contact", "Contact"]];
function ScrollTop() { const { pathname } = useLocation(); useEffect(() => window.scrollTo(0, 0), [pathname]); return null; }

function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="container nav-wrap">
    <Link to="/" className="brand" aria-label="Gerges Remon home"><span>GR</span><div>Gerges Remon<small>Digital Solutions & Creative Technology</small></div></Link>
    <button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open ? <X/> : <Menu/>}</button>
    <nav className={open ? "main-nav open" : "main-nav"} aria-label="Primary navigation">{nav.map(([to, label]) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({isActive}) => isActive ? "active" : ""}>{label}</NavLink>)}<a className="nav-cta" href={profile.resume} target="_blank" rel="noreferrer">Resume <ExternalLink size={15}/></a></nav>
  </div></header>;
}
function Footer() { return <footer><div className="container footer-grid"><div><strong>{profile.name}</strong><p>Turning business problems into systems, insights, and digital experiences.</p></div><div className="footer-links">{nav.slice(1).map(([to,label]) => <Link key={to} to={to}>{label}</Link>)}</div><div className="socials"><a href={profile.linkedin} aria-label="LinkedIn"><Linkedin/></a><a href={profile.github} aria-label="GitHub"><Github/></a><a href={`mailto:${profile.email}`} aria-label="Email"><Mail/></a></div></div><div className="container footer-bottom">© {new Date().getFullYear()} Gerges Remon. Built with purpose in Cairo.</div></footer> }
function Layout({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><Footer/></>; }
const Eyebrow = ({children}:{children:React.ReactNode}) => <p className="eyebrow">{children}</p>;
function SectionHead({kicker,title,body}:{kicker:string,title:string,body?:string}) { return <div className="section-head"><Eyebrow>{kicker}</Eyebrow><h2>{title}</h2>{body && <p>{body}</p>}</div>; }
function PageIntro({eyebrow,title,body}:{eyebrow:string,title:string,body:string}) { return <section className="page-intro"><div className="container"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{body}</p></div></section> }

function ProjectVisual({project}:{project:Project}) { return <div className={project.image ? "project-visual has-image" : "project-visual system-visual"}>{project.image ? <img src={project.image} alt={`${project.title} interface preview`} loading="lazy"/> : <><span>INPUT</span><i/><span>LOGIC</span><i/><span>INSIGHT</span></>}</div>; }
function ProjectCard({project}:{project:Project}) { return <article className="project-card"><ProjectVisual project={project}/><div className="project-copy"><div className="tag-row">{project.category.map(c=><span key={c}>{c}</span>)}</div><h3>{project.title}</h3><p>{project.summary}</p><dl><div><dt>Role</dt><dd>{project.role}</dd></div><div><dt>Outcome</dt><dd>{project.outcome}</dd></div></dl><div className="tool-row">{project.tools.slice(0,4).map(t=><span key={t}>{t}</span>)}</div><Link className="text-link" to={`/work/${project.slug}`}>View case study <ArrowRight size={17}/></Link></div></article> }

function Home() { const featured=projects.filter(p=>p.featured); return <Layout>
  <section className="hero"><div className="container hero-grid"><div><Eyebrow>Digital Solutions & Creative Technology</Eyebrow><h1>I turn business problems into <em>systems, insights,</em> and digital experiences.</h1><p className="hero-copy">I work across automation, data analysis, AI-assisted workflows, content, visual communication, and web development—connecting technology and creativity to build practical digital solutions.</p><div className="actions"><Link className="button primary" to="/work">Explore my work <ArrowRight size={18}/></Link><a className="button secondary" href={profile.resume} target="_blank" rel="noreferrer">Download CV</a><Link className="quiet-link" to="/contact">Let’s talk</Link></div></div><div className="hero-panel"><img src="/assets/main image.png" alt="Portrait of Gerges Remon"/><div><span>Based in Cairo</span><strong>Business-aware.<br/>Technical when needed.<br/>Clear by design.</strong></div></div></div><div className="container capability-strip"><span>Automation</span><span>Data</span><span>AI</span><span>Creative</span><span>Web</span></div></section>
  <section className="section"><div className="container"><SectionHead kicker="Selected work" title="Work that connects execution to a real business need." body="A mix of operational systems, analytical thinking, AI-assisted experiences, and web products."/><div className="project-list">{featured.map(p=><ProjectCard key={p.slug} project={p}/>)}</div><Link className="button secondary" to="/work">See all projects <ArrowRight size={18}/></Link></div></section>
  <section className="section soft"><div className="container"><SectionHead kicker="Capabilities" title="One problem may need more than one discipline."/><div className="capability-grid">{capabilities.map((c,i)=><article key={c.title}><span>0{i+1}</span><h3>{c.title}</h3><p>{c.description}</p><small>{c.solves}</small></article>)}</div><Link className="text-link" to="/capabilities">Explore capabilities <ArrowRight size={17}/></Link></div></section>
  <section className="section"><div className="container split"><SectionHead kicker="Business problems I solve" title="Less friction. Clearer information. Better communication."/><div className="problem-list"><div><b>01</b><p><strong>Manual work is taking too long.</strong> I map the workflow and build a practical automation layer.</p></div><div><b>02</b><p><strong>Data exists but decisions are still difficult.</strong> I clean, structure, and present what matters.</p></div><div><b>03</b><p><strong>A technical offer is hard to understand.</strong> I shape the content, hierarchy, and digital experience around its audience.</p></div></div></div></section>
  <section className="section dark"><div className="container journey"><SectionHead kicker="Professional journey" title="A broader practice, built one real need at a time."/><div className="journey-line">{["Web Development","Digital Content","Business Automation","Data Analysis","AI-Assisted Workflows","Integrated Solutions"].map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div></div></section>
  <section className="section"><div className="container final-cta"><Eyebrow>Have a practical problem to solve?</Eyebrow><h2>Let’s turn it into a clearer system, story, or digital experience.</h2><Link className="button primary" to="/contact">Start a conversation <ArrowRight size={18}/></Link></div></section>
  </Layout> }

function Work() { const cats=["All","Automation","Data","AI","Creative","Web","Business Systems"]; const [filter,setFilter]=useState("All"); const list=useMemo(()=>filter==="All"?projects:projects.filter(p=>p.category.includes(filter)),[filter]); return <Layout><PageIntro eyebrow="Selected projects" title="Proof lives in the work." body="Projects are presented around the problem, my actual role, the process, and the result—without invented metrics or vague technology lists."/><section className="section compact"><div className="container"><div className="filters" aria-label="Filter projects">{cats.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="project-list">{list.map(p=><ProjectCard key={p.slug} project={p}/>)}</div></div></section></Layout> }

function CaseStudy() { const {slug}=useParams(); const p=projects.find(x=>x.slug===slug); if(!p) return <Layout><PageIntro eyebrow="404" title="Project not found." body="The case study you requested does not exist."/></Layout>; return <Layout><section className="case-hero"><div className="container"><Link className="back" to="/work">← Back to work</Link><div className="tag-row">{p.category.map(c=><span key={c}>{c}</span>)}</div><h1>{p.title}</h1><p>{p.summary}</p><ProjectVisual project={p}/><div className="case-facts"><div><span>My role</span><p>{p.role}</p></div><div><span>Tools</span><p>{p.tools.join(" · ")}</p></div><div><span>Outcome</span><p>{p.outcome}</p></div></div></div></section><section className="section"><div className="container case-body"><article><span>01 / Context</span><h2>What was happening?</h2><p>{p.context}</p></article><article><span>02 / Problem</span><h2>What needed to improve?</h2><p>{p.problem}</p></article><article><span>03 / Approach</span><h2>How I framed the work.</h2><ul>{p.approach.map(x=><li key={x}>{x}</li>)}</ul></article><article><span>04 / Solution</span><h2>What I built or created.</h2><ul>{p.solution.map(x=><li key={x}>{x}</li>)}</ul></article><article><span>05 / Reflection</span><h2>What the work reinforced.</h2><p>{p.learning}</p></article>{(p.liveUrl||p.githubUrl)&&<article><span>06 / Links</span><h2>See the work.</h2><div className="actions">{p.liveUrl&&<a className="button primary" href={p.liveUrl} target="_blank" rel="noreferrer">Live project <ExternalLink size={17}/></a>}{p.githubUrl&&<a className="button secondary" href={p.githubUrl} target="_blank" rel="noreferrer">GitHub <Github size={17}/></a>}</div></article>}</div></section></Layout> }

function Capabilities() { return <Layout><PageIntro eyebrow="Capabilities" title="Technology, communication, and business context—working together." body="I choose the discipline around the problem, not the other way around."/><section className="section compact"><div className="container capability-detail">{capabilities.map((c,i)=><article key={c.title}><span>0{i+1}</span><div><h2>{c.title}</h2><p>{c.description}</p></div><div><small>Problems it helps solve</small><p>{c.solves}</p></div><div className="tool-row">{c.tools.map(t=><span key={t}>{t}</span>)}</div></article>)}</div><div className="container learning"><Eyebrow>Continuous development</Eyebrow><h2>Currently deepening the analytical side of the practice.</h2><p>Data analysis, business intelligence, SQL, Power BI, exploratory analysis, and responsible AI-assisted workflows.</p></div></section></Layout> }

function About() { return <Layout><PageIntro eyebrow="About" title="I started with interfaces. Real business work widened the view." body="Today, I approach digital work by understanding the problem first, then choosing the right mix of technology, data, automation, content, or design."/><section className="section compact"><div className="container about-grid"><div><img src="/assets/main image.png" alt="Gerges Remon"/></div><div className="prose"><h2>From building pages to building connected solutions.</h2><p>I began primarily with front-end development and digital interfaces. As I became more involved in real operational work, the questions changed: How can this report take less time? How can this data become useful? How can a technical product be easier to understand?</p><p>That work led me into business automation, data analysis, corporate communication, content systems, presentations, and AI-assisted production. Front-end development remains part of the toolkit, but it no longer defines the whole practice.</p><p>I now work at the intersection of business systems and digital communication—grounded by hands-on experience in an engineering and construction-solutions environment.</p><div className="about-note"><strong>Working principle</strong><p>Understand the business problem first. Build only what improves clarity, execution, or decision-making.</p></div></div></div><div className="container timeline"><div><span>2023–2027</span><h3>Computer Science</h3><p>New Cairo Academy</p></div><div><span>2024–2025</span><h3>Front-End Development</h3><p>150+ training hours at Route Academy</p></div><div><span>Current practice</span><h3>Integrated Digital Solutions</h3><p>Automation, data, AI-assisted workflows, content, design, and web.</p></div></div></section></Layout> }

function Contact() { const [sent,setSent]=useState(false); function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); const d=new FormData(e.currentTarget); const subject=encodeURIComponent(`${d.get("type")} inquiry from ${d.get("name")}`); const body=encodeURIComponent(`Name: ${d.get("name")}\nCompany: ${d.get("company")}\nTimeline: ${d.get("timeline")}\n\n${d.get("message")}`); window.location.href=`mailto:${profile.email}?subject=${subject}&body=${body}`; setSent(true);} return <Layout><PageIntro eyebrow="Contact" title="Tell me what needs to work better." body="Share the business problem, current workflow, or outcome you need. I’ll help identify the most useful next step."/><section className="section compact"><div className="container contact-grid"><form onSubmit={submit}><label>Name<input required name="name" autoComplete="name"/></label><label>Email<input required name="email" type="email" autoComplete="email"/></label><label>Company / Organization<input name="company" autoComplete="organization"/></label><label>Project type<select name="type" defaultValue="Automation / Business System">{["Automation / Business System","Data Analysis / Dashboard","AI Workflow","Content / Creative Project","Website / Front-End","Presentation / Company Profile","Consultation","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Timeline <span>(optional)</span><input name="timeline" placeholder="e.g. This month"/></label><label className="full">Message<textarea required name="message" rows={7} placeholder="What is happening now, and what would you like to improve?"/></label><button className="button primary" type="submit">Send inquiry <ArrowRight size={18}/></button>{sent&&<p className="form-note" role="status">Your email app should open with the inquiry prepared.</p>}</form><aside><Eyebrow>Direct contact</Eyebrow><a href={`mailto:${profile.email}`}><Mail/> {profile.email}</a><a href={`https://wa.me/20${profile.phone.slice(1)}`} target="_blank" rel="noreferrer"><Phone/> {profile.phone}</a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin/> LinkedIn</a><a href={profile.github} target="_blank" rel="noreferrer"><Github/> GitHub</a><p>{profile.location}<br/>Available for on-site and remote collaboration.</p></aside></div></section></Layout> }

export default function App(){return <BrowserRouter><ScrollTop/><Routes><Route path="/" element={<Home/>}/><Route path="/work" element={<Work/>}/><Route path="/work/:slug" element={<CaseStudy/>}/><Route path="/capabilities" element={<Capabilities/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Home/>}/></Routes></BrowserRouter>}
