export type Project = {
  slug: string; title: string; category: string[]; summary: string; problem: string;
  role: string; tools: string[]; image?: string; outcome: string; context: string;
  approach: string[]; solution: string[]; learning: string; liveUrl?: string;
  githubUrl?: string; featured?: boolean;
};

export const profile = {
  name: "Gerges Remon", email: "gergsremon26@gmail.com", phone: "01001016693",
  location: "Cairo, Egypt",
  resume: "https://drive.google.com/file/d/1M5xh7AB5blLfIV-7pTMxTPsqZ10xls_I/view?usp=sharing",
  github: "https://github.com/G-Remon",
  linkedin: "https://www.linkedin.com/in/gerges-remon-2625000n/",
};

export const projects: Project[] = [
  {
    slug: "business-productivity-system", title: "Business Productivity & Attendance System",
    category: ["Automation", "Business Systems", "Data"],
    summary: "A structured reporting system that turns recurring field updates into usable operational records.",
    problem: "Weekly updates and attendance records needed a consistent structure that reduced repetitive entry and made follow-up easier.",
    role: "Workflow analysis, information architecture, spreadsheet system design, Apps Script automation, and reporting logic.",
    tools: ["Google Sheets", "Google Apps Script", "Google Forms"], image: "/assets/Screenshot 2026-09-02 000917.png",
    outcome: "Created one connected workflow for collecting, organizing, and reviewing recurring operational data.",
    context: "Built for a real engineering and construction-solutions environment. Screens and data are intentionally anonymized to protect internal information.",
    approach: ["Mapped the recurring reporting flow", "Standardized inputs and validation", "Separated collection, processing, and review", "Designed around future date and team changes"],
    solution: ["Multi-day reporting workflow", "Automated row generation", "Attendance and absence classification", "Management-ready summary views"],
    learning: "The strongest automation starts with understanding how people already work—not with writing the script first.", featured: true,
  },
  {
    slug: "monthly-performance-analytics", title: "Monthly Performance Analytics",
    category: ["Automation", "Data", "Business Systems"],
    summary: "A reporting layer for comparing recurring work, surfacing patterns, and improving review quality.",
    problem: "Operational records existed, but monthly comparison and recurring-project analysis required too much manual review.",
    role: "Data structure, comparison logic, validation rules, reporting design, and dashboard refinement.",
    tools: ["Google Sheets", "Apps Script", "Excel"], image: "/assets/Screenshot 2026-09-02 001006.png",
    outcome: "Made recurring records easier to compare and prepared the workflow for more consistent management reporting.",
    context: "An internal business system presented here at workflow level only; private numbers and business logic are excluded.",
    approach: ["Defined meaningful monthly comparisons", "Handled duplicates and incomplete records", "Separated raw data from reporting", "Designed clear review states"],
    solution: ["Monthly comparison views", "Data-quality controls", "Recurring work analysis", "Reusable reporting structure"],
    learning: "A dashboard is only reliable when the data-entry and validation layers are designed with equal care.", featured: true,
  },
  {
    slug: "power-bi-dashboard", title: "Commercial Performance Dashboard",
    category: ["Data", "Business Systems"],
    summary: "An analytical dashboard built in Power BI to track key performance indicators and surface commercial insights.",
    problem: "Raw operational and sales data needed cleaning, modeling, and visualization before it could answer specific business questions about category performance and trends.",
    role: "Data cleaning, Power Query transformation, relational data modeling, DAX measure creation, and dashboard design.",
    tools: ["Power BI", "Excel"], image: "/assets/Screenshot 2026-09-02 010115.png",
    outcome: "Created a centralized analytical view that makes recurring reviews easier and surfaces actionable category performance.",
    context: "Developed as an analytical solution using raw operational data. Sensitive figures have been anonymized.",
    approach: ["Extracted and cleaned raw CSV and Excel data", "Established a robust relational data model", "Created DAX measures for KPIs", "Designed dashboard layout around key business questions"],
    solution: ["Automated Power Query cleaning pipeline", "Relational data model", "Interactive KPI tracking dashboard", "Clear insights panel"],
    learning: "Clear data modeling is more important than complex visualization; a good model makes the dashboard simple to build.", featured: true,
  },
  {
    slug: "mawazin-al-sharq", title: "Mawazin Al-Sharq", category: ["Web"],
    summary: "A responsive real-estate experience built around property discovery and clear user journeys.",
    problem: "The platform needed to present property information clearly and support search, filtering, and inquiry flows across devices.",
    role: "Front-end development, UI implementation, responsive behavior, API integration, and deployment.",
    tools: ["React", "Tailwind CSS", "React Query", "Swiper", "Vercel"], image: "/assets/Mawaazen image.png",
    outcome: "Delivered a production website with reusable components and responsive property browsing.",
    context: "A freelance web project developed from requirements through launch.",
    approach: ["Translated requirements into page flows", "Built reusable property UI", "Handled loading and API states", "Optimized layouts for mobile and desktop"],
    solution: ["Property discovery interface", "Search and filtering", "Responsive content hierarchy", "Production deployment"],
    learning: "Real product work requires balancing technical structure with the clarity users need to make decisions.",
    liveUrl: "https://www.mawazin-alsharq.com/", githubUrl: "https://github.com/G-Remon/mwazeen-elshark", featured: true,
  },
  {
    slug: "ai-resume-analyzer", title: "AI Resume Analyzer", category: ["AI", "Web"],
    summary: "An AI-assisted web experience for reviewing resumes against job requirements.",
    problem: "Candidates need a clearer way to identify gaps between a resume and a target job description.",
    role: "Front-end implementation, interaction design, responsive UI, and AI service integration.",
    tools: ["React", "TypeScript", "Tailwind CSS", "Claude Sonnet", "REST API"], image: "/assets/Ai resume image.png",
    outcome: "Built a responsive workflow that presents AI-generated feedback in an understandable format.",
    context: "A web project exploring practical, transparent use of generative AI in a focused user workflow.",
    approach: ["Defined a simple input-to-feedback flow", "Structured the response for scanning", "Designed clear loading and feedback states", "Kept AI output framed as guidance"],
    solution: ["Resume and job-description comparison", "Structured feedback", "Responsive interface", "AI-assisted recommendations"],
    learning: "AI becomes useful when its output is framed, reviewed, and presented around a specific decision.",
    liveUrl: "https://ai-analyzer-cv.vercel.app/", githubUrl: "https://github.com/G-Remon/ai-analyzer-cv", featured: true,
  },
  {
    slug: "ecommerce-experience", title: "E-commerce Experience", category: ["Web"],
    summary: "A complete storefront interface covering product discovery, cart, and checkout flows.",
    problem: "Build a coherent online-shopping journey with live data, reusable UI, and reliable state management.",
    role: "Front-end architecture, UI development, API integration, state management, and responsive implementation.",
    tools: ["React", "Redux Toolkit", "React Query", "Tailwind CSS", "Vercel"], image: "/assets/ecomerce image.png",
    outcome: "Delivered a responsive application with reusable commerce components and end-to-end shopping flows.",
    context: "A front-end product project focused on application architecture and real API behavior.",
    approach: ["Mapped the shopping journey", "Separated server and client state", "Built reusable product components", "Handled loading, error, and empty states"],
    solution: ["Product browsing", "Cart management", "Checkout flow", "Responsive interaction patterns"],
    learning: "Clear state boundaries make complex interfaces easier to maintain and easier for users to trust.",
    liveUrl: "https://ecommerce-2zg8.vercel.app/", githubUrl: "https://github.com/G-Remon/ecommerce",
  },
  {
    slug: "games-discovery-platform", title: "Games Discovery Platform",
    category: ["Web"],
    summary: "A responsive web application for discovering, filtering, and exploring a large library of games.",
    problem: "Needed a fast, responsive interface to handle a large dataset of games with filtering and search capabilities across platforms and genres.",
    role: "Front-end architecture, UI development, API integration, and responsive implementation.",
    tools: ["React", "JavaScript", "CSS", "REST API"], image: "/assets/games image.png",
    outcome: "Delivered an interactive web application that handles dynamic data smoothly across devices.",
    context: "A front-end development project focusing on API integration, client-side filtering, and responsive UI patterns.",
    approach: ["Mapped the user journey for game discovery", "Built reusable UI components for game cards", "Implemented client-side filtering logic", "Optimized the layout for different screen sizes"],
    solution: ["Game discovery grid", "Category and platform filtering", "Detailed game view pages", "Responsive navigation"],
    learning: "Managing loading states and image optimization is critical when dealing with content-heavy external APIs.",
    featured: true,
  },
  {
    slug: "construction-chemicals-catalogue", title: "Construction Chemicals Catalogue",
    category: ["Creative", "Business Systems"],
    summary: "A structured, visually clear product catalogue designed in InDesign for engineering and construction professionals.",
    problem: "Technical product information was scattered and difficult for consultants and clients to navigate, lacking a consistent visual hierarchy.",
    role: "Content architecture, layout design, visual hierarchy planning, and final print-ready production in Adobe InDesign.",
    tools: ["Adobe InDesign", "Adobe Photoshop", "Content Strategy", "Print Production"], image: "/assets/catalog.png",
    outcome: "Created a reusable communication format that makes technical products easier to understand, specify, and present to clients.",
    context: "Developed for a real engineering and construction-chemicals environment.",
    approach: ["Categorized products by engineering application", "Built a clear information hierarchy for technical specs", "Designed a grid system in InDesign for consistency", "Standardized product imagery and tables"],
    solution: ["Comprehensive product catalogue", "Clear technical spec tables", "Consistent visual language", "Print and digital-ready formats"],
    learning: "Technical communication works best when accuracy, audience context, and visual hierarchy are developed together.", featured: true,
  },
  {
    slug: "weather-app", title: "Weather Forecast App",
    category: ["Web"],
    summary: "A clean, responsive weather application that delivers real-time forecasts with an intuitive visual interface.",
    problem: "Users needed a fast, visually clear way to check current conditions and multi-day forecasts without navigating cluttered interfaces.",
    role: "Front-end development, API integration, UI design, and responsive implementation.",
    tools: ["React", "JavaScript", "CSS", "Weather API"], image: "/assets/Weather image.png",
    outcome: "Delivered a lightweight, responsive weather app with real-time data and a polished user experience.",
    context: "A front-end project focused on consuming external APIs and presenting dynamic data in a visually engaging way.",
    approach: ["Designed a minimal UI around key weather data", "Integrated a live weather API", "Built responsive layouts for mobile and desktop", "Handled loading and error states gracefully"],
    solution: ["Real-time weather display", "Multi-day forecast view", "Location-based search", "Responsive design"],
    learning: "Presenting dynamic external data well requires careful attention to loading states, error handling, and visual hierarchy.",
  },
];

export const capabilities = [
  { title: "Automation & Business Systems", description: "I map repetitive workflows and turn them into structured tools that support real operations.", solves: "Reporting, attendance, data entry, recurring tasks", tools: ["Apps Script", "Google Sheets", "Google Forms"] },
  { title: "Data & Analytics", description: "I clean, structure, and analyze business data so it becomes easier to understand and act on.", solves: "Data quality, KPI tracking, comparison, reporting", tools: ["Excel", "SQL", "Power BI", "Power Query"] },
  { title: "AI-Assisted Workflows", description: "I use generative AI deliberately across research, ideation, content, visuals, and production.", solves: "Research synthesis, production support, ideation", tools: ["Prompt Engineering", "AI Research", "Image & Video AI"] },
  { title: "Content & Visual Communication", description: "I connect business context with content systems, product storytelling, and corporate communication.", solves: "Technical content, campaigns, product explanation", tools: ["Content Strategy", "Photoshop", "Social Content"] },
  { title: "Design & Presentation", description: "I structure complex information into clear presentations, profiles, catalogues, and visual systems.", solves: "Information hierarchy, executive communication", tools: ["PowerPoint", "InDesign", "Photoshop"] },
  { title: "Web & Front-End Development", description: "I build responsive digital interfaces with clean component structures and practical user journeys.", solves: "Landing pages, corporate sites, product interfaces", tools: ["React", "TypeScript", "Tailwind", "Vercel"] },
];
